---
- hosts: localhost
  vars_files:
    - vars/variables.yml

  tasks:
    - name: configure git
      git_config:
        name: "{{ item.name }}"
        scope: global
        value: "{{ item.value }}"
      with_items:
        - { name: 'user.email', value: 'me@dockerbot' }
        - { name: 'user.name', value: 'DockerBot' }

    - include: update_plays.yml


