---
- hosts: localhost

  tasks:
  - name: configure git
    git_config:
      name: "{{ item.name }}"
      scope: global
      value: "{{ item.value }}"
    with_items:
      - { name: 'user.email', value: 'me@dockerbot' }
      - { name: 'user.name', value: 'DockerBot' }

  - name: clone or update integration tests repo
    git:
      repo: "{{ cfme_repo }}"
      dest: "{{ cfme_repo_dir }}"
      version: "{{ cfme_branch }}"

  - name: clone or update yamls
    git:
      repo: "{{ cfme_data_repo }}"
      dest: "{{ cfme_data_dir }}"
      version: "{{ cfme_data_branch }}"
    environment:
      GIT_SSL_NO_VERIFY: true

  - name: run full env setup
    command: "python -m cfme.scripting.quickstart"
    args:
      chdir: "{{  cfme_repo_dir }}"

  - name: add env.local.yaml with env setup

  - name: check gpg keys exist

  - name: checkout PR and apply changes
  - name: re-install packages if those are affected
  - name: run collect only smoke test
  - name: run smoke tests if necessary
  - name: collect artifacts and make them available
  - name: git verify commit

  - name: push results